### ISSUE TITLE
Sonar PHP plugin url no longer available

### ISSUE THREAD

**Issue by aoturoa** [geerlingguy/drupalci-sonar-jenkins#12]
The absolute URL specified in the /provisioning/vars/main.yml file is no longer available.
An alternative can be found here:

http://downloads.sonarsource.com/plugins/org/codehaus/sonar-plugins/php/sonar-php-plugin/1.2/sonar-php-plugin-1.2.jar

**Comment by geerlingguy** [comment]
Thanks for finding that! I hadn't run the playbook in a while, and it seems that domain got dropped and never redirected.
