### ISSUE TITLE
"Failed to connect to the host via ssh" when running vagrant provision

### ISSUE THREAD

**Issue by dhayalanms** [geerlingguy/drupalci-sonar-jenkins#19]
A2ML10780M:codeaudit dhayalan$ vagrant provision
==> drupalci: Running provisioner: ansible...
    drupalci: Running ansible-playbook...

PLAY [drupalci] ****************************************************************

TASK [setup] *******************************************************************
fatal: [192.168.99.9]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.99.9 port 22: Operation timed out\r\n", "unreachable": true}
	to retry, use: --limit @/Users/dhayalan/codeaudit/provisioning/playbook.retry

PLAY RECAP *********************************************************************
192.168.99.9               : ok=0    changed=0    unreachable=1    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
@dhayalanms - Can you check versions of Ansible, Vagrant, and VirtualBox?

Paste the output from the following command: `vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version`

**Comment by dhayalanms** [comment]
Finally I was able to make it work by updating the virtual box.

**Comment by geerlingguy** [comment]
@dhayalanms - Great!
