### ISSUE TITLE
Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.

### ISSUE THREAD

**Issue by zied-ellouze** [geerlingguy/drupalci-sonar-jenkins#4]
Hi,
when I launch the vm "vagrant up", i have a problem

zied@Zied-Ellouze:~/workspace/vagrant/drupalci-sonar-jenkins$ vagrant up
Bringing machine 'drupalci' up with 'virtualbox' provider...
==> drupalci: Importing base box 'centos64'...
==> drupalci: Matching MAC address for NAT networking...
==> drupalci: Setting the name of the VM: drupalci-sonar-jenkins_drupalci_1420988031410_53917
==> drupalci: Clearing any previously set forwarded ports...
==> drupalci: Clearing any previously set network interfaces...
==> drupalci: Preparing network interfaces based on configuration...
    drupalci: Adapter 1: nat
    drupalci: Adapter 2: hostonly
==> drupalci: Forwarding ports...
    drupalci: 22 => 2222 (adapter 1)
==> drupalci: Running 'pre-boot' VM customizations...
==> drupalci: Booting VM...
==> drupalci: Waiting for machine to boot. This may take a few minutes...
    drupalci: SSH address: 127.0.0.1:2222
    drupalci: SSH username: vagrant
    drupalci: SSH auth method: private key
    drupalci: Warning: Connection timeout. Retrying...
    drupalci: Warning: Connection timeout. Retrying...
    drupalci: Warning: Connection timeout. Retrying...
    drupalci: Warning: Connection timeout. Retrying...
    drupalci: Warning: Connection timeout. Retrying...
    drupalci: Warning: Remote connection disconnect. Retrying...
    drupalci: Warning: Remote connection disconnect. Retrying...
    drupalci: Warning: Remote connection disconnect. Retrying...
    drupalci: 
    drupalci: Vagrant insecure key detected. Vagrant will automatically replace
    drupalci: this with a newly generated keypair for better security.
    drupalci: 
    drupalci: Inserting generated public key within guest...
    drupalci: Removing insecure key from the guest if its present...
    drupalci: Key inserted! Disconnecting and reconnecting using new SSH key...
==> drupalci: Machine booted and ready!
==> drupalci: Checking for guest additions in VM...
    drupalci: The guest additions on this VM do not match the installed version of
    drupalci: VirtualBox! In most cases this is fine, but in rare cases it can
    drupalci: prevent things such as shared folders from working properly. If you see
    drupalci: shared folder errors, please make sure the guest additions within the
    drupalci: virtual machine match the version of VirtualBox you have installed on
    drupalci: your host and reload your VM.
    drupalci: 
    drupalci: Guest Additions Version: 4.2.10
    drupalci: VirtualBox Version: 4.3
==> drupalci: Setting hostname...
==> drupalci: Configuring and enabling network interfaces...
==> drupalci: Mounting shared folders...
    drupalci: /vagrant => /home/zied/workspace/vagrant/drupalci-sonar-jenkins
==> drupalci: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/home/zied/workspace/vagrant/drupalci-sonar-jenkins/.vagrant/machines/drupalci/virtualbox/private_key --user=vagrant --connection=ssh --limit='drupalci' --inventory-file=provisioning/inventory-local --sudo provisioning/playbook.yml
ERROR: cannot find role in /home/zied/workspace/vagrant/drupalci-sonar-jenkins/provisioning/roles/geerlingguy.munin-node or /home/zied/workspace/vagrant/drupalci-sonar-jenkins/provisioning/geerlingguy.munin-node or /etc/ansible/roles/geerlingguy.munin-node
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

How can I resolve this problem?

Thanks

**Comment by zied-ellouze** [comment]
I install vagrant plugin install vagrant-vbguest
actuallay I have this input
Bringing machine 'drupalci' up with 'virtualbox' provider...
==> drupalci: Clearing any previously set forwarded ports...
==> drupalci: Clearing any previously set network interfaces...
==> drupalci: Preparing network interfaces based on configuration...
    drupalci: Adapter 1: nat
    drupalci: Adapter 2: hostonly
==> drupalci: Forwarding ports...
    drupalci: 22 => 2222 (adapter 1)
==> drupalci: Running 'pre-boot' VM customizations...
==> drupalci: Booting VM...
==> drupalci: Waiting for machine to boot. This may take a few minutes...
    drupalci: SSH address: 127.0.0.1:2222
    drupalci: SSH username: vagrant
    drupalci: SSH auth method: private key
    drupalci: Warning: Connection timeout. Retrying...
    drupalci: Warning: Connection timeout. Retrying...
    drupalci: Warning: Remote connection disconnect. Retrying...
==> drupalci: Machine booted and ready!
GuestAdditions 4.3.10 running --- OK.
==> drupalci: Checking for guest additions in VM...
==> drupalci: Setting hostname...
==> drupalci: Configuring and enabling network interfaces...
==> drupalci: Mounting shared folders...
    drupalci: /vagrant => /home/zied/workspace/vagrant/drupalci-sonar-jenkins
==> drupalci: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/home/zied/workspace/vagrant/drupalci-sonar-jenkins/.vagrant/machines/drupalci/virtualbox/private_key --user=vagrant --connection=ssh --limit='drupalci' --inventory-file=provisioning/inventory-local --sudo provisioning/playbook.yml
ERROR: cannot find role in /home/zied/workspace/vagrant/drupalci-sonar-jenkins/provisioning/roles/geerlingguy.munin-node or /home/zied/workspace/vagrant/drupalci-sonar-jenkins/provisioning/geerlingguy.munin-node or /etc/ansible/roles/geerlingguy.munin-node
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
This should be fixed in the most recent commit (see above). Thanks for reporting!
