### ISSUE TITLE
Error on vagrant up on v1.2.0/master

### ISSUE THREAD

**Issue by tenken** [geerlingguy/drupalci-sonar-jenkins#5]
Hi I'm new to CI and hope this project is a good turnkey solution? I'm getting this error after installing the dependancies and trying "vagrant up"

```
✔ aw-dgurba ~/apps/drupalCI/drupalci-sonar-jenkins-master > vagrant up
Bringing machine 'drupalci' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* The following settings shouldn't exist: insert_key

vm:
* The box 'geerlingguy/centos6' could not be found.
```

Any feedback is appreciated :)

**Comment by geerlingguy** [comment]
It seems that you might have an old version of Vagrant - can you run `vagrant -v` and see what version you get? It should be at least 1.7.x.

**Comment by tenken** [comment]
Ah, you are correct.

Ubuntu 14.04 LTS and 14.10 have version 1.4.3 in their repositories (I always opt to go distribution first before other channels).

I have upgraded vagrant to 1.7.2 from the official site's .deb package and the project seems to be building fine.

Thanks!

**Comment by geerlingguy** [comment]
Great! Yeah, 1.4.3 is really old.
