### ISSUE TITLE
Add support for CSSLint, JSLint & Qunit

### ISSUE THREAD

**Issue by legovaer** [geerlingguy/drupalci-sonar-jenkins#9]
Enhancement suggestion;

Theming is a part of Drupal. Therefore, it might be useful to include a code-analysis on the css & js files as well. 

This is already included in the Jenkins drupal template (https://github.com/reload/jenkins-drupal-template)

**Comment by geerlingguy** [comment]
This project is being deprecated (though the underlying roles are still maintained); please see https://github.com/geerlingguy/drupalci-sonar-jenkins/issues/27
